services:
  # Bike Sales Agent API
  bike-agent:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - DB_NAME=${DB_NAME}
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - bike-agent-network

  # Ollama LLM Server
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - bike-agent-network

volumes:
  ollama_data:

networks:
  bike-agent-network:
    driver: bridge